# Generated by Django 3.2.6 on 2021-10-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='root_Note',
        ),
    ]
