# Generated by Django 3.2.6 on 2021-10-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_root_note_comment_root_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='title',
            new_name='folder',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='body',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
