# Generated by Django 3.2.6 on 2022-02-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment_root_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
